---
# tasks file for systemd-journal-upload
#

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution and version-specific vars.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      skip: true

- name: Check the presence of all mandatory variables
  ansible.builtin.include_tasks: check_mandatory_vars.yml

- name: Install the systemd-journal-upload package
  ansible.builtin.package:
    name: "{{ __systemd_journal_upload_package }}"
    state: present

- name: Template systemd-journal-upload configuration file
  ansible.builtin.template:
    src: systemd-journal-upload.conf.j2
    dest: /etc/systemd/journal-upload.conf
    owner: root
    group: root
    mode: '0640'
  notify:
    - Reload systemd
    - Restart systemd-journal-upload.service

- name: Enable systemd-journal-upload services
  ansible.builtin.systemd:
    name: {{ item }}
    enabled: yes
  loop:
    - systemd-journal-upload.service
